name: Radiant Church
favicon: null
layout_spectrum: 0.08835766604170203
typography_spectrum: 0.57191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7272458614315838
  lightness: 0.8565791782457381
  saturation: 0.2585513743106276
  rhythmicContrast: 0.6301940854173154
purpose: []
